image: node:iron

pipelines:
  default:
    - step:
        name: 'Run Chromatic'
        caches:
          - node
        script:
          - corepack enable
          - pnpm install
          - pnpm chromatic -- --project-token=$CHROMATIC_PROJECT_TOKEN
  pull-requests:
    feature/*:
      - step:
          name: 'Run Chromatic'
          script:
            - corepack enable
            - pnpm install
            - pnpm chromatic -- --project-token=$CHROMATIC_PROJECT_TOKEN
