import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from './providers';

import '@mantine/core/styles.css';
import '@glasshouse/components/styles.css';
import '@glasshouse/components/tailwind.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
			</head>
			<body className={inter.className}>
				<Providers>
					<MantineProvider>{children}</MantineProvider>
				</Providers>
			</body>
		</html>
	);
}
