import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Providers } from './providers';

import '@glasshouse/components/styles.css';
import '@mantine/core/styles.css';
import './globals.css';

const geist = Geist({ variable: '--font-geist', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Glasshouse Components Demo',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
			</head>
			<body className={`${geist.variable} ${geistMono.variable} ${geist.className} antialiased`}>
				<Providers>
					<MantineProvider>{children}</MantineProvider>
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
